secretflow/scql

cmd/scdbclient/main.go
* https://github.com/secretflow/scql/issues/19
=> fix scdbclient panic

.circleci/config.yml
* macOS ut only runs on main branch
* monthly regtest no longer triggers ut
=> Reduce circleci workload

engine/framework/session.cc
=> support group by string

docs/locales/zh_CN/LC_MESSAGES/reference/mysql_compatibility.po
[将 SCQL《MySQL Compatibility》英文文档逐句翻译成中文文档#70](https://github.com/secretflow/scql/issues/70)
=> add mysql_compatibility doc in Chinese

docs/update_po.sh
ref https://github.com/secretflow/secretflow/pull/559, update the update_po.sh to run well.
=> fix:update sh file to run well

docs/locales/zh_CN/LC_MESSAGES/reference/scql_status.po
[docs] add scql_status doc in chinese
=> [docs] add scql_status doc in chinese

docs/locales/zh_CN/LC_MESSAGES/development/integrate_scql_system.po
=> [docs]  add integrate scql system in chinese

engine/bazel/engine_deps.bzl
* fix deadlock in ecdhpsi when setting up link throttle window
=> update spu to 0.4.1b1 

docs/locales/zh_CN/LC_MESSAGES/getting_started/scql_intro.po
[docs] add sql intro doc in Chinese
=> [docs] add sql intro doc in Chinese

pkg/expression/expression_to_stmt.go, pkg/planner/core/testdata/runsql_in.json
在SCQL中实现单方算子abs
https://github.com/secretflow/scql/issues/112
I have read the CLA Document and I hereby sign the CLA
=> feat:add single party func abs

pkg/expression/expression_to_stmt.go, pkg/planner/core/testdata/runsql_in.json
在SCQL中实现单方算子round
https://github.com/secretflow/scql/issues/113
I have read the CLA Document and I hereby sign the CLA
=> feat:add single party func round

pkg/expression/expression_to_stmt.go, pkg/planner/core/testdata/runsql_in.json
在SCQL中实现单方算子floor
https://github.com/secretflow/scql/issues/115
=> feat:add single party func floor

pkg/expression/expression_to_stmt.go, pkg/planner/core/testdata/runsql_in.json
在SCQL中实现单方算子instr
Fixed: https://github.com/secretflow/scql/issues/117
=> feat:add single party func instr

docker/scql.Dockerfile
set TARGETPLATFORM env in scql.Dockerfile
=> fix:build_image_for_arm_env

api/generate_proto.sh
=> fix: fix make pb error in dev container

.circleci/unittest-config.yml, docs/locales/zh_CN/LC_MESSAGES/index.po, docs/locales/zh_CN/LC_MESSAGES/reference/centralized-deploy-config.po, docs/locales/zh_CN/LC_MESSAGES/reference/engine-config.po, docs/locales/zh_CN/LC_MESSAGES/reference/operators.po, docs/locales/zh_CN/LC_MESSAGES/reference/p2p-deploy-config.po, docs/locales/zh_CN/LC_MESSAGES/topics/deployment/run-scql-on-kuscia.po, docs/reference/engine-config.rst, docs/reference/operators.md, docs/topics/deployment/run-scql-on-kuscia.rst
- add translation for 0.7.0
- skip go short test
=> modify docs

WORKSPACE, engine/bazel/engine_deps.bzl
=> fix compile erorr without `-c opt` option

cmd/regtest/testdata/single_party.json, cmd/regtest/testdata/two_parties.json, pkg/interpreter/translator/translator.go
=> Revert "[chore] refine input queries for regression test and fix typo"

docs/topics/deployment/how-to-deploy-centralized-cluster.rst
Reverts secretflow/scql#511
FYI：@EtanWatson @baikeqichenwei @FollyCoolly 
The original codeblock format is rendered incorrectly, so I will revert this commit.
=> Revert "Docs/#484 add messages"

.circleci/config.yml
=> ci: update path-filtering

pkg/interpreter/translator/translator_ccl_input_for_test.go, pkg/planner/core/expression_rewriter.go
support query like 
`SELECT ta.ID, ta.date FROM ta right join tb on ta.ID = tb.ID where ta.age between '2025-04-23 12:25:42' and '2025-05-23 12:25:42';`
=> feat: support between and

.ci/script/check-whitespace.sh, .github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/whitespace-check.yml, .licenserc.yaml, pkg/broker/application/app.go
=> chore(ci): add Go vuln check and whitespace linter
